package Funciones;

import java.util.ArrayList;
import java.util.List;

public class Descripcion {

    public static String BKD(String codigo, String maquina){

        List<String> lista;

        if(maquina.equals("TPR881")){
            lista = Lista_BKD04();
        }else{
            lista = Lista_BKD06();
        }

        int cod = Integer.parseInt(codigo);
        return lista.get(cod);
    }

    private static List<String> Lista_BKD06(){

        List<String> lista = new ArrayList<>();

        lista.add("		");
        lista.add("Error No. 1	EMERGENCY STOP Pressed, or machine made TOTAL stop (ERR).");
        lista.add("Error No. 2	Air supply pressure too low (under 0,4 Mpa).");
        lista.add("Error No. 3	Malfunction of machine position detector, electronic cam (BC1, BC2).");
        lista.add("Error No. 4	Main supply lines interchanged or a supply line voltage missing - 3x400V (PX1).");
        lista.add("Error No. 5	Thermal and Electric current protecion QM1 for vacuum pump M8 is switched off.");
        lista.add("Error No. 6	Sealing temperature on G1 out of tolerance adjusted by regulator NR1.");
        lista.add("Error No. 7	Sealing temperature on G2 out of tolerance adjusted by regulator NR2.");
        lista.add("Error No. 8	Machine covers mustn`t be opened during the machine run.");
        lista.add("Error No. 9	Visual system communication failed. Check signal is not running. Reset VS of PC.");
        lista.add("Error No. 10	Manual handle was used during machine run  (sensor BQ33).");
        lista.add("Error No. 11	Turret safety clutch was opened. (sensor BQ34)");
        lista.add("Error No. 12	24V / 2.1A DC  power supply was overloaded. (OMRON)");
        lista.add("Error No. 13	24V / 8A DC power supply was overloaded . (AXIMA)");
        lista.add("Error No. 14	100V AC power supply (for small AC motors) was overloaded.");
        lista.add("Error No. 15	Vacuum pump is not switched on, the machine can not run in the AUTO mode.");
        lista.add("Error No. 16	Malfunction of the main motor M1 frequency converter or servo driver (BKD06).");
        lista.add("Error No. 17	Check 2nd bend position, (sensor BQ14).");
        lista.add("Error No. 18	Safety clutch on cutting unit opened (sensor BQ35). Shift of LF has not been finished.");
        lista.add("Error No. 19	24V DC power supply was overloaded. (TM1 - small electric box).");
        lista.add("Error No. 20	The Vacuum on machine is below limit (sensor BP1).");
        lista.add("Error No. 21	Missing chip in carrier tape at unit G1 (sensor BQ171). Add it manually !  Without chip machine can not run.");
        lista.add("Error No. 22	Missing chip in carrier tape at unit G2 (BQ172). Add it manually !  Without chip machine can not run.");
        lista.add("Error No. 23	Stepping motor M61 on G1 is not in the proper position (sensor BQ161), press INIC button.");
        lista.add("Error No. 24	Stepping motor M62 on G2 is not in the proper position (sensor BQ162), press INIC button.");
        lista.add("Error No. 25	");
        lista.add("Error No. 26	");
        lista.add("Error No. 27	");
        lista.add("Error No. 28	");
        lista.add("Error No. 29	Rear charger is empty, reach the end position. Insert new, full one and press ERR button.");
        lista.add("Error No. 30	");
        lista.add("Error No. 31	");
        lista.add("Error No. 32	LF are probably not in the magazine. Selected number of attempts about finding was reached.");
        lista.add("Error No. 33	");
        lista.add("Error No. 34	");
        lista.add("Error No. 35	Bad chip unload, chip must not be on sensor BQ15.  It is necessary to remove it !");
        lista.add("Error No. 36	Bad chip unload, missing for taping into G1, chip is not detected by sensor BQ15 ! Preselected fault number reached.");
        lista.add("Error No. 37	Taping of preselected number of reels is finished on G1, cut the reel off and start machine. !(CAMEA37)!");
        lista.add("Error No. 38	");
        lista.add("Error No. 39	");
        lista.add("Error No. 40	");
        lista.add("Error No. 41	Error of PC triggering. PC did not confirm TRIG signal until time of measurement data reading.");
        lista.add("Error No. 42	Bad setting of control panel, only one special function for sorting can be chosen.");
        lista.add("Error No. 43	Problem with stepping motor M61. During INIC the sensor BQ161 is not activated within 2,5sec.");
        lista.add("Error No. 44	Problem with stepping motor M62. During INIC the sensor BQ162 is not activated within 2,5sec.");
        lista.add("Error No. 45	Taping of preselected number of reels finished on G2, cut the reel off and start machine. !(CAMEA45)!");
        lista.add("Error No. 46	");
        lista.add("Error No. 47	");
        lista.add("Error No. 48	Preselected number of missing chips on measurement position reached, or bad chip continuously measured.");
        lista.add("Error No. 49	Preselected number of missing chips on THI measurement reached, or bad chip continuously measured.");
        lista.add("Error No. 50	Yield on THI measurement is under limit !");
        lista.add("Error No. 51	Sensor BQ171 (100 % filling G1) is constantly inactive.");
        lista.add("Error No. 52	Sensor BQ172 (100 % filling G2) is constantly inactive");
        lista.add("Error No. 53	After measurement start the signal THI_L_OK remained in active level.");
        lista.add("Error No. 54	After measurement start the signal THI_H_OK remained in active level.");
        lista.add("Error No. 55	After measurement start the signal THI_D_OK remained in active level.");
        lista.add("Error No. 56	After measurement start the signal THI_U_OK remained in active level.");
        lista.add("Error No. 57	PC did not finish THI measurement in preselected time.");
        lista.add("Error No. 58	");
        lista.add("Error No. 59	The machine made preselected number of consecutive iddle cycles");
        lista.add("Error No. 60	");
        lista.add("Error No. 61	");
        lista.add("Error No. 62	Chip printing on taping unit G1 (K4) is out of tolerance.");
        lista.add("Error No. 63	Chip printing on taping unit G2 (K3) is out of tolerance.");
        lista.add("Error No. 64	");
        lista.add("Error No. 65	");
        lista.add("Error No. 66	");
        lista.add("Error No. 67	");
        lista.add("Error No. 68	");
        lista.add("Error No. 69	Problem with the main motor M1 rotation. The time limit for 1 turret cycle was exceeded.");
        lista.add("Error No. 70	Stepping function is blocked by turret rotation error.");
        lista.add("Error No. 71	");
        lista.add("Error No. 72	");
        lista.add("Error No. 73	Control unit M61 does not communicate in the  time limit (200ms).");
        lista.add("Error No. 74	Control unit M62 does not communicate in the time limit (200ms).");
        lista.add("Error No. 75	Sealing head on G1 did not lift up in the preselected time to the basic position.");
        lista.add("Error No. 76	Sealing head on G2 did not lift up in the preselected time to the basic position.");
        lista.add("Error No. 77	Sealing head on G1 did not move to basic position in time limit. Is necessary to speed up the movement.");
        lista.add("Error No. 78	Sealing head on G2 did not move to basic position in time limit. Is necessary to speed up the movement.");
        lista.add("Error No. 79	Stepping motor M61 on G1 is electrically disconected from MAN. panel, it is not possible to use INIC function.");
        lista.add("Error No. 80	Stepping motor M62 on G2 is electrically disconected from MAN. panel, it is not possible to use INIC function.");
        lista.add("Error No. 81	");
        lista.add("Error No. 82	");
        lista.add("Error No. 83	Visual system did not confirm start of the camera K5 (terminalside) (VK5=1), make RESET of PC CAMEA");
        lista.add("Error No. 84	Statistical error on camera K5=CONTACT (terminal side) from machine control system.");
        lista.add("Error No. 85	Taping unit G1 can not make the required step, she is blocked by error.");
        lista.add("Error No. 86	Taping unit G2 can not make the required step, she is blocked by error.");
        lista.add("Error No. 87	Visual system has problems in data processing or in the machine communication . (OK=0  RDAT=1)  !(CAMEA8)!");
        lista.add("Error No. 88	Statistical error from visual system CVS801.   (VSEOL=0)   Bend or LF.   !(CAMEA63)!");
        lista.add("Error No. 89	Visual system is blocking the machine (OK=0 or RDAT=0)");
        lista.add("Error No. 90	Visual system is reporting the end of printing camera K1 (LF) calibration  (OK=0  RDAT=0)    !(CAMEAKP)!");
        lista.add("Error No. 91	Statistical error on the camera BEND (K2) from machine control system.");
        lista.add("Error No. 92	Statistical error on the camera LF (K1) from machine control system.");
        lista.add("Error No. 93	Visual system is storing important data to HDD. After 10sec start the machine again. (OK=1  RDAT=0) !(CAMEAS)!");
        lista.add("Error No. 94	Visual system did not confirm the start of camera BEND (K2)   (VO=1), make RESET of PC  CAMEA");
        lista.add("Error No. 95	Visual system did not confirm the start of camera G2 (K3) (VP2=1), make RESET of PC  CAMEA");
        lista.add("Error No. 96	Visual system did not confirm the start of camera G1 (K4)   (VP1=1), make RESET of PC  CAMEA");
        lista.add("Error No. 97	Visual system did not confirm the start of camera LF (K1) snapshot  (VP31=1), make RESET of PC  CAMEA");
        lista.add("Error No. 98	Visual system did not confirm the start of camera LF (K1)  static shot (VP32=1), make RESET of PC  CAMEA");
        lista.add("Error No. 99	Machine reverse movement. Turn manually the handle forward until the INIC is blinking.");
        lista.add("Error No. 100	Transport of the cutting unit is not in the initial position. Check the clutch and press INIC.");
        lista.add("Error No. 101	");
        lista.add("Error No. 102	");
        lista.add("Error No. 103	Problem with LF transport on the cutting unit. ONE-STEP is not finished.  Check the clutch.");
        lista.add("Error No. 104	Problem with LF transport on the cutting unit. DOUBLE-STEP is not finished.  Check the clutch.");
        lista.add("Error No. 105	Cutting unit is not properly adjusted. It is necessary to do the calibration.");
        lista.add("Error No. 106	If the turret is not in the init. pos. (angle OUT 16) it is not possible to start calibration of cutting station.");
        lista.add("Error No. 107	");
        lista.add("Error No. 108	Calibration of cutting station was not successfuly finished, it was interrupted.");
        lista.add("Error No. 109	");
        lista.add("Error No. 110	");
        lista.add("Error No. 111	");
        lista.add("Error No. 112	Calibration of cutting station is running.");
        lista.add("Error No. 113	Placing plate on G1 is not in the working position.");
        lista.add("Error No. 114	Placing plate on G2 is not in the working position.");
        lista.add("Error No. 115	Bad placed chip into unit G1. It is necessary to remove him (do not move the carrier tape).");
        lista.add("Error No. 116	Bad placed chip into unit G2. It is necessary to remove him (do not move the carrier tape).");
        lista.add("Error No. 117	");
        lista.add("Error No. 118	");
        lista.add("Error No. 119	");
        lista.add("Error No. 120	");
        lista.add("Error No. 121	Reading of the printing calibration results !(CAMEA121)!");
        lista.add("Error No. 122	Rear charger is disconnected, check it");
        lista.add("Error No. 123	Front charger is disconnected, check it");
        lista.add("Error No. 124	The rear charger of pushing unit LF is disconnected, check it");
        lista.add("Error No. 125	Powered unwindings are disconnected, check it");
        lista.add("Error No. 126	");
        lista.add("Error No. 127	Calibration results are not corresponding to requirements. Remove LF, check BQ25 and continue.");
        lista.add("Error No. 128	Reel on G1 contains chips which were not checked by visual system.");
        lista.add("Error No. 129	Reel on G2 contains chips which were not checked by visual system.");
        lista.add("Error No. 130	During initialization in back direction, the control unit of M61 does not communicate within time limit or movement by hand on G1.");
        lista.add("Error No. 131	During initialization in back direction, the control unit of M62 does not communicate within time limit or movement by hand on G2.");
        lista.add("Error No. 132	");
        lista.add("Error No. 133	In the exploitation mode both reels (G1 and G2) are finished.");
        lista.add("Error No. 134	In the exploitation mode the reel on G2 is finished, it`s necessary to cut it out.");
        lista.add("Error No. 135	Taping of the joined reels is finished. Enter the new batch (print of the report).");
        lista.add("Error No. 136	The check window on G1 was opened above the checked chip, to check chip again press INIC button.");
        lista.add("Error No. 137	The check window on G2 was opened above the checked chip, to check chip again press INIC button.");
        lista.add("Error No. 138	");
        lista.add("Error No. 139	Precharging error. Number of preselected errors was reached. Check the contacts.");
        lista.add("Error No. 140	");
        lista.add("Error No. 141	");
        lista.add("Error No. 142	");
        lista.add("Error No. 143	");
        lista.add("Error No. 144	Error of ejected parts sensor.");
        lista.add("Error No. 145	");
        lista.add("Error No. 146	Horizontal cylinder of sealing on G1 did not finish movement in time limit.");
        lista.add("Error No. 147	Horizontal cylinder of sealing on G2 did not finish movement in time limit.");
        lista.add("Error No. 148	");
        lista.add("Error No. 149	");
        lista.add("Error No. 150	Power supply outage, it is necessary to do the calibration of cutting station.");
        lista.add("Error No. 151	");
        lista.add("Error No. 152	");
        lista.add("Error No. 153	");
        lista.add("Error No. 154	Rear charger is not initialized, movement is not possible, press START button (on the front panel).");
        lista.add("Error No. 155	Cylinder YV-24 movement ( lift up of motor M13 ) is not done in the time limit.");
        lista.add("Error No. 156	Stepping motor M13 at loading station is not in the initial position (problem of initialization).");
        lista.add("Error No. 157	The LF remained in the loading station, it is not possible to move with the charger ( sensor BQ52 ).");
        lista.add("Error No. 158	Piston of LF pushing is outside, it is not posible to move with charger.");
        lista.add("Error No. 159	LF did not leave the sensor BQ52 in the required time limit (blowing out of LF).");
        lista.add("Error No. 160	LF did not reach the sensor BQ53 in the required time limit (remove him or insert under sensor).");
        lista.add("Error No. 161	LF was jammed on the stepping motor in loading station (he did not leave the sensor BQ53)");
        lista.add("Error No. 162	At the request for LF pushing-out, the sensor BQ52 is active (remove LF from station)");
        lista.add("Error No. 163	At the request for LF pushing-out the sensor BQ56 is active (remove LF from station)");
        lista.add("Error No. 164	LF did not reach the sensor BQ59 (at leaving the machine). Insert him under sensor.");
        lista.add("Error No. 165	At leaving the machine the LF did not leave the sensor BQ59 in the preselected time limit.");
        lista.add("Error No. 166	Cylinder YV-23 movement (LF inserting into the front magazine) unfinished in time limit (SQ 231)");
        lista.add("Error No. 167	LF on the sensor BQ59. Remove it, he can not leave the machine automatically.");
        lista.add("Error No. 168	Front charger is full. Insert new empty magazines and press ERROR");
        lista.add("Error No. 169	Front charger is not initialized, movement is not possible, press START button (on the left side of front panel)");
        lista.add("Error No. 170	Sensor BQ11 in cutting station didn`t detect the end of LF, she is stopped down too long time; check it.");
        lista.add("Error No. 171	Cutting station was disconnected, it is necessary to calibrate it again.");
        lista.add("Error No. 172	Taping unit G1 was disconnected, it is necessary to do reset of reel on G1.");
        lista.add("Error No. 173	Taping unit G2 was disconnected, it is necessary to do reset of reel on G2.");
        lista.add("Error No. 174	Problem with LF pushing-out from the magazine (sensor BQ36)");
        lista.add("Error No. 175	First round of the SPK (calibration), take LF and insert him to the machine again.");
        lista.add("Error No. 176	TimeOut of unwinding motor M23 was exceeded (unit G1)");
        lista.add("Error No. 177	TimeOut of unwinding motor M24 was exceeded (unit G2)");
        lista.add("Error No. 178	Cover glass on G1 is not in the working position");
        lista.add("Error No. 179	Cover glass on G2 is not in the working position");
        lista.add("Error No. 180	PC is not in the stand-by mode when the measurement starts.");
        lista.add("Error No. 181	PC did not confirm the measurement start.");
        lista.add("Error No. 182	PC did not finish measurement in the preselected time.");
        lista.add("Error No. 183	After the measurement start, signal PRIM_Q1 remained in active level.");
        lista.add("Error No. 184	After the measurement start, signal PRIM_Q2 remained in active level.");
        lista.add("Error No. 185	After the measurement start, signal SEC_Q1 remained in active level.");
        lista.add("Error No. 186	After the measurement start, signal SEC_Q2 remained in active level.");
        lista.add("Error No. 187	After the measurement start, signal CONT_OK remained in active level.");
        lista.add("Error No. 188	The actual carrier tape position on G1 is higher then the required, it`s necessary to move the tape backwards");
        lista.add("Error No. 189	The actual carrier tape position on G1 is lower then the required, it`s necessary to the move tape forwards");
        lista.add("Error No. 190	The actual carrier tape position on G2 is higher then the required, it`s necessary to move the tape backwards");
        lista.add("Error No. 191	The actual carrier tape position on G2 is lower then the required, it`s necessary to move the tape forwards");
        lista.add("Error No. 192	Error of the precharging source 1 (first position), check pulses do not come.");
        lista.add("Error No. 193	Error of the precharging source 2 (second position - measurement), check pulses do not come");
        lista.add("Error No. 194	In mode without sorting (Q1 = Q2) same results for Q1 and Q2 do not come (error of signals from PC)");
        lista.add("Error No. 195	Bad LF type (lead/lead free). Take out LF from the cutting station. Call the technologist.");
        lista.add("Error No. 196	Error during LF type detection (lead/lead free). Take out LF from cutting station.");
        lista.add("Error No. 197	");
        lista.add("Error No. 198	Carrier tape is back (IRC) and camera window on G1 was opened. Batch has to go to 100% visual inspection.");
        lista.add("Error No. 199	Carrier tape is back (IRC) and camera window on G2 was opened. Batch has to go to 100% visual inspection.");
        lista.add("Error No. 200	");
        lista.add("Error No. 201	Pick-up station is not in the initial position (BQ163).");
        lista.add("Error No. 202	Initialization of stepping motor (M63) of pick up station is not finished in time limit.");
        lista.add("Error No. 203	Problem of communication with the stepping motor card (DM455).");
        lista.add("Error No. 204	The actual carrier tape position on the pick-up station is higher then the required, move tape backwards or RESET.");
        lista.add("Error No. 205	The actual carrier tape position on the pick-up station is lower then the required, move tape forwards or RESET.");
        lista.add("Error No. 206	Sensor BQ163 (initial position of the stepping motor M63 , pick-up station) is permanent inactive.");
        lista.add("Error No. 207	Sensor BQ41 (chip presence in pick-up position ) is permanent inactive.");
        lista.add("Error No. 208	Sensor BQ41 is active, even the chip passed through (bad inserted carrier tape of chip size C,D)");
        lista.add("Error No. 209	Problem with carrier tape initial position searching before switch-over of the changer (BQ164, BQ165)");
        lista.add("Error No. 210	Problem of carrier tape initial position after switch-over of the changer (BQ164, BQ165)");
        lista.add("Error No. 211	Before switch-over of the changer the covers were opened.");
        lista.add("Error No. 212	Covers were opened during switch-over of the changer.");
        lista.add("Error No. 213	Cover tape was broken - upper position (BQ31)");
        lista.add("Error No. 214	Cover tape was broken - lower position (BQ32)");
        lista.add("Error No. 215	Cylinder of changer did not reach the movement in limit, he remained in upper position. SQ261 was not activated.");
        lista.add("Error No. 216	Cylinder of changer did not reach the movement in limit, he remained in lower position. SQ262 was not activated.");
        lista.add("Error No. 217	Cylinder of changer clutch did not reach the movement in limit. The cylinder is outside. SQ301 was not activated.");
        lista.add("Error No. 218	Cylinder of changer clutch did not reach the movement in limit. The cylinder is inside. SQ302 was not activated.");
        lista.add("Error No. 219	It is not possible to do manual movement of changer, the clutch is switched ON (CYL 30).");
        lista.add("Error No. 220	Moving part of changer is disconnected.");
        lista.add("Error No. 221	The fixed part of changer is disconnected.");
        lista.add("Error No. 222	The fixed part of changer was disconnected, it is necessary to RESET the pick-up station.");
        lista.add("Error No. 223	Calibration measurement finished. Remove calibration chip!");
        lista.add("Error No. 224	");
        lista.add("Error No. 225	");

        return lista;
    }

    private static List<String> Lista_BKD04(){

        List<String> lista = new ArrayList<>();

        lista.add("		");
        lista.add("Error No. 1	Uno de los botones de EMERGENCIA ha sido pulsado, o la máquina realizó un paro total (ERR).");
        lista.add("Error No. 2	Baja presión en el abastecimiento de aire comprimido (menos  0,4MPa).");
        lista.add("Error No. 3	Falla en el mecanismo de registro de la posición de la máquina, sensor etc. (BC1, BC2)");
        lista.add("Error No. 4	Error en la secuencia o la ausencia de todas las fases de entrada de corriente electrica 3x400V (PX1).");
        lista.add("Error No. 5	Caída de corriente y protección termica FA4 del motor de la bomba del vacío (M8).");
        lista.add("Error No. 6	La temperatura de sellado en la G1,está fuera de la tolerancia ajustada con la alarma en el regulador NR1.");
        lista.add("Error No. 7	La temperatura de sellado en la G2, está fuera de la tolerancia ajustada con la alarma en el regualdor NR2.");
        lista.add("Error No. 8	La máquina en marcha no debe tener sus protecciones abiertas.");
        lista.add("Error No. 9	El sistema visual no se comunica con la máquina. La señal de control no funciona. Resetee la computadora.");
        lista.add("Error No. 10	Durante la marcha de la máquina ha sido manipulada la manivela (sensor BQ33).");
        lista.add("Error No. 11	Ocurrió un resbalamiento del acoplamiento dentado en la tracción del carrusel. (sensor BQ34)");
        lista.add("Error No. 12	Se ha cortado la fuente de 24V, 2.1A ss estable. (OMRON)");
        lista.add("Error No. 13	Se ha cortado la fuente de 24V, 8A ss inestable. (AXIMA)");
        lista.add("Error No. 14	Se ha cortado la fuente de 100V st para los motores pequeños.");
        lista.add("Error No. 15	Atención, la bomba de vacío no está encendida. Sin la bomba la máquina no funciona en el modo AUTO.");
        lista.add("Error No. 16	Falla en el funcionamiento del modificador de frecuencia del motor principal M1 o servo (en BKD06).");
        lista.add("Error No. 17	El segundo doblez está mal hecho, revíselo (sensor BQ14).");
        lista.add("Error No. 18	Deslizamiento en el acoplamiento de la estación de recorte (sensor BQ35). El movimiento del LF no se ha realizado.");
        lista.add("Error No. 19	Se ha cortado la fuente de 24V ss inestable. (TM1 - distribuidor pequeño).");
        lista.add("Error No. 20	El vacío en la máquina está fuera del límite (sensor BP1).");
        lista.add("Error No. 21	Falta un capacitor en el blister en G1(sensor BQ171). Añadirlo manualmente. Sin este la máquina no se puede poner en marcha.");
        lista.add("Error No. 22	Falta un capacitor en el blister en G2(sensor BQ172). Añadirlo manualmente. Sin este la máquina no se puede poner en marcha.");
        lista.add("Error No. 23	El motor de paso M61 en G1 no está en su posición inicial(sensor BQ161), pulse el botón INIC.");
        lista.add("Error No. 24	El motor de paso M62 en G2 no está en su posición inicial(sensor BQ162), pulse el botón INIC.");
        lista.add("Error No. 25	Falla de los sensores de caída de LF a la máquina (sensor BQ1 hasta BQ7), todas inactivas. ");
        lista.add("Error No. 26	El movimiento horizontal no está en la posición zero(sensor BQ6 no funciona). No se puede mover verticalmente.");
        lista.add("Error No. 27	Camara  apagada ENCENDER!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        lista.add("Error No. 28	");
        lista.add("Error No. 29	El cargador de atrás está vacío, llegó al final. Introduzca uno nuevo, pulse el botón ERR.");
        lista.add("Error No. 30	El magazin no se puede mover, LF está fuera del magazin.(sensor BQ8 está tapado).");
        lista.add("Error No. 31	Despues de haber salido del magazin el LF se trabó, no ha llegado al sensor BQ92 en su límite de tiempo.");
        lista.add("Error No. 32	Probablemente en el magazin no hay LF. Se agotó el número preestablecido de intentos para buscarlos.");
        lista.add("Error No. 33	El giro de la mesa giratoria no se terminó en el límite de tiempo. Revise el sensor SQ191 y SQ192");
        lista.add("Error No. 34	Durante el transporte de LF a la rampa para su caída, esta no llegó en el límite de tiempo.");
        lista.add("Error No. 35	Capacitor malo en sensor BQ 15, por favor remuevalo!");
        lista.add("Error No. 36	Hace falta un capacitor en el sensor BQ 15, la acción fue repetida según la preselección.");
        lista.add("Error No. 37	El carrete en G1 está completo. Introduzca uno nuevo e inicie la máquina. !(CAMEA37)!");
        lista.add("Error No. 38	El desplazamiento vertical no está en posición de trabajo(iniciativo BQ3). No se puede mover horizontalmente !!");
        lista.add("Error No. 39	Falla del motor M3 o en sus sensores de mando.(Desplazamiento vertical del magazin).");
        lista.add("Error No. 40	Falla del motor M4 o en sus sensores de mando.Desplazamiento horizontal del magazin).");
        lista.add("Error No. 41	Falla en el control de medición del PC. El PC no ha confirmado la señal TRIG en el momento de leer los datos de la medición.");
        lista.add("Error No. 42	El tablero de mando está mal ajustado. Sólo se puede elegir una función especial de selección.");
        lista.add("Error No. 43	Problema con el motor de paso M61. En INIC el sensor BQ161 no está activado a los 2,5 seg.");
        lista.add("Error No. 44	Problema con el motor de paso M62. En INIC el sensor BQ162 no está activado a los 2,5 seg.");
        lista.add("Error No. 45	Terminado el sellado de los carretes preescogidos en G2, corte el carrete y encienda de nuevo la máquina. !(CAMEA45)!");
        lista.add("Error No. 46	El LF, durante el movimiento en la mesa giratoria, no llegó en el límite de tiempo. Mueva el LF manualmente debajo del sensor y pulse el boton ERR.");
        lista.add("Error No. 47	El LF, durante el movimiento de salida de la mesa giratoria a la rampa, no llegó en el límite de tiempo.");
        lista.add("Error No. 48	Falta una cantidad de capacitores recortados para medición según la preselección asignada o fue detectada una pieza defectuosa según la asignación anterior.");
        lista.add("Error No. 49	El LF está vacío, al ser rechzado de la máquina, se quedó trabado al final del transportador. Retírelo.");
        lista.add("Error No. 50	El cambio de vías en la mesa giratoria no se terminó en el límite de tiempo. Hay que revisar los sensores SQ en los cilindros neumáticos.");
        lista.add("Error No. 51	El sensor BQ171 (carga de 100 % de G1) está inactivo permanentemente.");
        lista.add("Error No. 52	El sensor BQ172 (carga de 100 % de G2) está inactivo permanentemente.");
        lista.add("Error No. 53	La mesa giratoria está ocupada, quite el obstáculo y pulse ERR(LF saldrá fuera de la máquina.");
        lista.add("Error No. 54	La mesa giratoria está ocupada, quite el obstáculo y pulse ERR (LF irá a una segunda vuelta)");
        lista.add("Error No. 55	El movimiento de la estación de volteo-COSTADOS-no se terminó en el límite de tiempo.");
        lista.add("Error No. 56	El movimiento de la estación de volteo-CENTRO-no se terminó en el límite de tiempo.");
        lista.add("Error No. 57	El movimiento de la estación de volteo-TRANSPORTADOR-no se terminó en el límite de tiempo.");
        lista.add("Error No. 58	El movimiento de la estación de volteo-CARGAGO-no se terminó en le límite de tiempo.");
        lista.add("Error No. 59	La máquina ha hecho el número de toques consecutivos, programados por Ud, en vacío.");
        lista.add("Error No. 60	LF se ha trabado durante su introducción a la estación de corte. No se mueve. No fue activado BQ11.");
        lista.add("Error No. 61	");
        lista.add("Error No. 62	La impresión del capacitor en la G1 está fuera del límite de tolerancia. CAMARA 4  !(CAMEA61)!");
        lista.add("Error No. 63	La impresión del capacitor en la G2 está fuera del límite de tolerancia. CAMARA 3  !(CAMEA62)!");
        lista.add("Error No. 64	");
        lista.add("Error No. 65	El magazin no se puede trasladar, el LF está salido del magazin ( BQ9 activado).");
        lista.add("Error No. 66	El magazín no se puede trasladar, no está metido el pistón de sacado de LF ( SQ11 ).");
        lista.add("Error No. 67	No se cumplen las condiciones para el arranque del motor M3(paso vertical).(BQ6 no está activado).");
        lista.add("Error No. 68	No se cumplen las condiciones para el arranque del motor M4(paso horizontal).  (BQ3 no está activado)");
        lista.add("Error No. 69	Problema durante el giro del motor principal(M1). Fue traspasado el límite de tiempo para la realización de un toque del carusel");
        lista.add("Error No. 70	La función de marcar el paso del carusel está bloqueada por un error en el giro del carusel.");
        lista.add("Error No. 71	");
        lista.add("Error No. 72	");
        lista.add("Error No. 73	La unidad de mando M61 no comunica en el límite de tiempo de 200ms.");
        lista.add("Error No. 74	La unidad de mando M62 no comunica en el límite de tiempo de 200ms.");
        lista.add("Error No. 75	La cabeza selladora en G1 no se levantó a su posición básica en el límite de tiempo programado.");
        lista.add("Error No. 76	La cabeza selladora en G2 no se levantó a su posición básica en el límite de tiempo programado.");
        lista.add("Error No. 77	La cabeza selladora en G1 no llegó a tiempo a la posición de operación. Hay que accelerar su movimiento.");
        lista.add("Error No. 78	La cabeza selladora en G2 no llegó a tiempo a la posición de operación. Hay que accelerar su movimiento.");
        lista.add("Error No. 79	El motor de paso M61 en G1 está desconectado de la electricidad del tablero MAN, no se puede usar la función INIC.");
        lista.add("Error No. 80	El motor de paso M62 en G2 está desconectado de la electricidad del tablero MAN, no se puede usar la función INIC.");
        lista.add("Error No. 81	");
        lista.add("Error No. 82	");
        lista.add("Error No. 83	");
        lista.add("Error No. 84	");
        lista.add("Error No. 85	La G1 no puede hacer el paso requerido,está bloqueada por un error.");
        lista.add("Error No. 86	La G2 no puede hacer el paso requerido, está bloqueada por un error.");
        lista.add("Error No. 87	El sistema visual anuncia problemas en el manejo de datos o en la comunicación con la máquina. (OK=0  RDAT=1)  !(CAMEA8)!");
        lista.add("Error No. 88	Error estadístico del sistema visual CVS801.   (VSEOL=0)   Doblado o LF.   !(CAMEA63)!");
        lista.add("Error No. 89	El sistema visual está bloqueando la máquina (OK=0 o RDAT=0)");
        lista.add("Error No. 90	El sistema visual anuncia el final de la calibración de la cámara de LF K1.  (OK=0  RDAT=0)    !(CAMEAKP)!");
        lista.add("Error No. 91	Error estadístico en la cámara K2-DOBLADO del sistema de control de la máquina. !(CAMEA63)!");
        lista.add("Error No. 92	Error estadístico en la cámara K1=LF del sistema de control de la máquina.   !(CAMEAL)!");
        lista.add("Error No. 93	El sistema visual está ingresando datos al disco de la computadora. Despues de 10 seg ponga la máquina en marcha. (OK=1  RDAT=0) !(CAMEAS)!");
        lista.add("Error No. 94	El sistema visual no ha confirmado el inicio de la cámara K2 (doblado) (VO=1), haga el RESET  PC  CAMEA");
        lista.add("Error No. 95	El sistema visual no ha confirmado el inicio de la cámara K3 (G2)   (VP2=1), haga el RESET  PC  CAMEA");
        lista.add("Error No. 96	El sistema visual no ha confirmado el inicio de la cámara K4 (G1)   (VP1=1), haga RESET  PC  CAMEA");
        lista.add("Error No. 97	El sistema visual no ha confirmado el inicio de la cámara K1 (LF) imágen rápida  (VP31=1), haga RESET  PC  CAMEA");
        lista.add("Error No. 98	El sistema visual no ha confirmado el inicio de la cámara K1 (LF) imágen estática (VP32=1), haga RESET  PC  CAMEA");
        lista.add("Error No. 99	Sucedió una marcha de retroceso de la empacadora.Gire la manivela manualmente hacia adelante mientras parpadea INIC.");
        lista.add("Error No. 100	El movimiento de la unidad recortadora no está en su posición inicial.Revise el acople y presione INIC.");
        lista.add("Error No. 101	");
        lista.add("Error No. 102	");
        lista.add("Error No. 103	Problema en el paso del LF hacia el recorte. No se ha realizado todo el PASO UNICO. Revise el embrague.");
        lista.add("Error No. 104	Problema en el paso del LF hacía el recorte. No se ha realizado todo el DOBLE PASO. Revise el embrague.");
        lista.add("Error No. 105	La estación del corte no está bien ajustada. Hay que calibrarla.");
        lista.add("Error No. 106	No se puede arrancar la calibración de la estación de corte si el carusel no está en su posición inicial (ángulo OUT 16).");
        lista.add("Error No. 107	");
        lista.add("Error No. 108	La calibración de la estación de corte no ocurrió co exito, fue interrumpida.");
        lista.add("Error No. 109	Durante el movimiento vertical del magazin, el sensor BQ6 no está activado( Avance horizontal no está centrado alrededor del 0 ).");
        lista.add("Error No. 110	Durante el movimiento vertical del magazin, el sensor SQ11 no está activado( cilindro neumático del empuje de LF )");
        lista.add("Error No. 111	Durante el movimiento vertical del cargador, el electroimán de sujecció del magazin está salido.");
        lista.add("Error No. 112	Está en marcha la calibración de la estación de corte.");
        lista.add("Error No. 113	La placa de inserción de G1 no está en la posición de trabajo.");
        lista.add("Error No. 114	La placa de inserción de G2 no está en la posición de trabajo.");
        lista.add("Error No. 115	El capacitor está mal colocado en G1. Es necesario retirarlo (no mover el blister).");
        lista.add("Error No. 116	El capacitor está mal colocado en G2. Es necesario retirarlo (no mover el blister).");
        lista.add("Error No. 117	");
        lista.add("Error No. 118	");
        lista.add("Error No. 119	");
        lista.add("Error No. 120	");
        lista.add("Error No. 121	Lectura de los resultados de la calibración del estampado.!(CAMEA121)!");
        lista.add("Error No. 122	El cargador de atrás está desconectado, revíselo.                             ");
        lista.add("Error No. 123	El cargador de adelante está desconectado, revíselo.                            ");
        lista.add("Error No. 124	La rampa para la entrada de LF del cargador de atrás está desconectada, revísela.    ");
        lista.add("Error No. 125	Desembobinados obligatorios están desconectados, revíselos.                          ");
        lista.add("Error No. 126	");
        lista.add("Error No. 127	Los resultados de la calibración no cumplen con los requerimientos. Retire el LF, revise el BQ25 y continue.");
        lista.add("Error No. 128	El carrete de G1 contiene capacitores no  revisados por el sistema visual.");
        lista.add("Error No. 129	El carrete de G2 contiene capacitores no revisados por el sistema visual.");
        lista.add("Error No. 130	");
        lista.add("Error No. 131	");
        lista.add("Error No. 132	");
        lista.add("Error No. 133	Durante la extracción, se han acabado los dos carretes (G1 y G2).");
        lista.add("Error No. 134	Durante la extracción se ha acabado el carrete en G2. Es necesario cortarlo.");
        lista.add("Error No. 135	Terminó el empacado del carrete añadido. Realice la programación para un nuevo lote (impresión del reporte).");
        lista.add("Error No. 136	");
        lista.add("Error No. 137	");
        lista.add("Error No. 138	");
        lista.add("Error No. 139	Falla en la precarga. La falla se ha repetido según la preselección. Revise los contactos en los baleros.");
        lista.add("Error No. 140	Durante el traslado horizontal del magazín, el sensor BQ3 no está activado (el movimiento vertical en al posición inicial).");
        lista.add("Error No. 141	Durante el traslado horizontal del magazín, el sensor SQ11 no está activado (el cilindro neumático de empuje de LF).");
        lista.add("Error No. 142	Durante el traslado horizontal del magazín, el sensor BQ8 está activado( LF está salido del magazín).");
        lista.add("Error No. 143	Durante el traslado horizontal del magazín, el sensor BQ9 está activado( LF está salido del magazín).");
        lista.add("Error No. 144	Defecto del sensor SCRAR(de caídas).");
        lista.add("Error No. 145	Durante la salida de la LF, mesa giratoria está ocupada.");
        lista.add("Error No. 146	El cilindro neumático horizontal de sellado en G1, no ha terminado su función en el límite de tiempo.");
        lista.add("Error No. 147	El cilindro neumático horizontal de sellado en G2, no ha terminado su función en el límite de tiempo.");
        lista.add("Error No. 148	");
        lista.add("Error No. 149	");
        lista.add("Error No. 150	Se produjo un corte electrico. Es necesario hacer la calibración de la estación de corte.");
        lista.add("Error No. 151	");
        lista.add("Error No. 152	");
        lista.add("Error No. 153	");
        lista.add("Error No. 154	El cargador de atrás no se ha arrancado, no se puede mover, pulse el botón START (a la izquierda, en la parte de enfrente).");
        lista.add("Error No. 155	El movimiento del cilindro neumático YV-24 ( levanta el motor M13 ) no se ha terminado en el tiempo de límite.");
        lista.add("Error No. 156	El motor de paso M13 en la estación de la llegada no está en su posición inicial  (problema con la inicialización).");
        lista.add("Error No. 157	En la estación de la llegada se trabó unaLF, no se puede mover el cargador ( sensor BQ52 ).");
        lista.add("Error No. 158	Se quedó salido el pistón del empuje de LF, no se puede mover el cargador.");
        lista.add("Error No. 159	LF no salió del sensor BQ52 en el límite ajustado(salida de LF).");
        lista.add("Error No. 160	LF no llegó al sensor BQ53 en el límite ajustado (retírelo o pongalo debajo del sensor).");
        lista.add("Error No. 161	LF se trabó en el motor de paso en la estación de la llegada (no abandonó el sensor BQ53)");
        lista.add("Error No. 162	Al requerir el empuje de la LF,el sensor BQ52 está activado(retire la LF de la estación)");
        lista.add("Error No. 163	Al requerir el empuje de la LF, el sensor BQ56 está activado (retire LF de la estación)");
        lista.add("Error No. 164	La LF, al salir de la máquina, no ha llegado al sensor BQ59. Es necesario moverlo debajo del sensor.");
        lista.add("Error No. 165	La LF,al salir de la máquina,no abandonó el sensor BQ59  en el límite preseleccionado.");
        lista.add("Error No. 166	El movimiento del cilindro neumático YV-23 (entrada de LF al cargador de delante) no se terminó en el límite (SQ 231)");
        lista.add("Error No. 167	LF está en el sensor BQ59. Hay que retirarlo, no será empujado.");
        lista.add("Error No. 168	El cargador delantero está lleno. Inserte nuevos magazines vacíos y pulse el ERROR.");
        lista.add("Error No. 169	El cargador delantero no se ha arrancado, no se puede mover, pulse el botón START (parte delantera a la izquierda)");
        lista.add("Error No. 170	El sensor BQ11 en la estación de corte no detectó el final de la LF, está tapado demasiado tiempo; revíselo.");
        lista.add("Error No. 171	La estación de corte está desconectada, es necesario calibrarla de nuevo.");
        lista.add("Error No. 172	La G1 está desconectada, hay que hacer el reset del carrete G1.");
        lista.add("Error No. 173	La G2 está desconectada, hay que hacer el reset del carrete G2.");
        lista.add("Error No. 174	Problema al empujar la LF del magazín (sensor BQ60)");
        lista.add("Error No. 175	Primera vuelta de SPK(calibración del estampado), tome la LF e insertela otra vez en la máquina.");
        lista.add("Error No. 176	Está sobrepasado el TimeOut para la marcha del motor del desenrollamiento M23 (para G1)");
        lista.add("Error No. 177	Está sobrepasado el TimeOut para la marcha del motor del desenrollamiento M24 (para G2)");
        lista.add("Error No. 178	Vidrio protector en G1 no está en la posición del trabajo.");
        lista.add("Error No. 179	Vidrio protector en G2 no está en la posición del trabajo.");
        lista.add("Error No. 180	Al iniciar la medición, la PC no está en el estado inicial.");
        lista.add("Error No. 181	PC no ha confirmado el inicio de la medición.");
        lista.add("Error No. 182	PC no ha terminado la medición en el tiempo preseleccionado.");
        lista.add("Error No. 183	A partir del inicio de la medición, la señal PRIM_Q1 se ha quedado en el nivel activo.");
        lista.add("Error No. 184	A partir del inicio de la medición, la señal PRIM_Q2 se ha quedado en el nivel activo.");
        lista.add("Error No. 185	A partir del inicio de la medición, la señal SEC_Q1 se ha quedado en el nivel activo.");
        lista.add("Error No. 186	A partir del inicio de la medición, la señal SEC_Q2 se ha quedado en el nivel activo.");
        lista.add("Error No. 187	A partir del inicio de la medición, la señal CONT_OK se ha quedado en el nivel activo.");
        lista.add("Error No. 188	La posición actual del blister en G1 es superior que la requerida, hay que mover el blister hacia atrás.");
        lista.add("Error No. 189	La posición actual del blister en G1 es inferior que la requerida, hay que mover el blister hacia adelante.");
        lista.add("Error No. 190	La posición actual del blister en G2 es superior que la requerida, hay que mover el blister hacia atrás.");
        lista.add("Error No. 191	La posición actual del blister en G2 es inferior que la requerida, hay que mover el blister hacia adelante.");
        lista.add("Error No. 192	Falla de la fuente de precarga 1 (posición primera), no llegan los impulsos de control");
        lista.add("Error No. 193	Falla de la fuente de precarga 2 (posición segunda - medición), no llegan los impulsos de control");
        lista.add("Error No. 194	En el regimen sin clasificación (Q1 = Q2) no llegan los recuerdos iguales para Q1 a Q2 (falla de las señales de PC)");
        lista.add("Error No. 195	");
        lista.add("Error No. 196	");
        lista.add("Error No. 197	");
        lista.add("Error No. 198	");
        lista.add("Error No. 199	");
        lista.add("Error No. 200	");
        lista.add("Error No. 201	Estación de separación  no está en su posición inicial (BQ163).");
        lista.add("Error No. 202	Inicialización del motor de paso de la estación de separación (M63) no se terminó en el límite de tiempo.");
        lista.add("Error No. 203	Problema en la comunicación con la tarjeta del motor de paso (DM455).");
        lista.add("Error No. 204	La posición actual de la cinta en la separación es superior que la requerida, hay que moverla atrás (o RESET). ");
        lista.add("Error No. 205	La posición actual de la cinta en la separación es inferior que la requerida, hay que adelantarla (o RESET). ");
        lista.add("Error No. 206	El sensor BQ163 (la posición inicial del motor de paso de la separación M63) está permanentemente inactiva.");
        lista.add("Error No. 207	El sensor BQ41 (capacitor presente en la posición de selección) está permanentemente inactiva.");
        lista.add("Error No. 208	El sensor BQ41 está activado, aunque acaba de pasar un capacitor (el blister mal puesto del tamaño C,D)");
        lista.add("Error No. 209	Problema encontrar la posición inicial del blister antes de conmutar el changer (BQ164, BQ165)");
        lista.add("Error No. 210	Problema en la posición inicial del blister despues de haber conmutado el changer(BQ164, BQ165)");
        lista.add("Error No. 211	Antes de conmutar el changer, sus protecciones han sido abiertas.");
        lista.add("Error No. 212	Al conmutar el changer, sus protecciones han sido abiertas.");
        lista.add("Error No. 213	Se ha quebrado el cover tape - posición de arriba (BQ31)");
        lista.add("Error No. 214	Se ha quebrado el cover tape - posición de abajo (BQ32)");
        lista.add("Error No. 215	El cilindro neumático del changer no logró moverse en el límite de tiempo, se quedó arriba. El SQ261 no se activó.");
        lista.add("Error No. 216	El cilindro neumático del changer no logró moverse en el límite de tiempo, se quedó abajo. El SQ262 no se activó.");
        lista.add("Error No. 217	El cilindro neumático del clutch del changer no logró moverse en el límite, se quedó salido. El SQ301 no se activó.");
        lista.add("Error No. 218	El cilindro neumático del clutch del changer no logró moverse en el límite, se quedó metido. El SQ302 no se activó.");
        lista.add("Error No. 219	El changer no se puede mover a mano, el clutch está cerrado(encendido) (CYL 30).");
        lista.add("Error No. 220	La parte móvil del changer está desconectada.");
        lista.add("Error No. 221	La parte fija del changer está desconectada.");
        lista.add("Error No. 222	Se han desconectado las partes fijas del changer, hay que hacer el RESET de la unidad de separación.");
        lista.add("Error No. 223	");
        lista.add("Error No. 224	");
        lista.add("Error No. 225	");
        lista.add("Error No. 226	");

        return lista;
    }
}
